### ISSUE TITLE
Cannot make Blazor app run on linux

### ISSUE THREAD

**Issue by MathiasLui** [tryphotino/photino.Blazor#126]
I hope this is the right place to come, I wanted to make a Blazor hybrid app but for Windows and Linux and found this to be really fitting theoretically. Since none of the presets contained a blazor preset, I started with a blazor example app and changed it in a way to look like the Blazor sample app. On Windows it runs as expected but on linux not so much...  

To make sure, I tried the same but with the Photino Blazor Sample app. I ran `dotnet build .\Photino.Blazor.Sample.csproj -r linux-x64 --self-contained` and as expected I got an ELF.  
On kali it gave me some error about not finding some library that was actually in the folder. Gave up and after weeks/months I tried the same again but running it on Zorin (Ubuntu).  

This time I just get an exception which is the same for my app and the sample app:  
```
Unhandled exception. System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager.StaticWebAssetsLoader.<>c.<UseStaticWebAssets>b__0_0(String path)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager.StaticWebAssetsLoader.UseStaticWebAssets(IFileProvider fileProvider)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager..ctor(IServiceProvider provider, Dispatcher dispatcher, Uri appBaseUri, IFileProvider fileProvider, JSComponentConfigurationStore jsComponents, String hostPageRelativePath)
   at Photino.Blazor.PhotinoWebViewManager..ctor(PhotinoWindow window, IServiceProvider provider, Dispatcher dispatcher, IFileProvider fileProvider, JSComponentConfigurationStore jsComponents, IOptions`1 config)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Photino.Blazor.ServiceCollectionExtensions.<>c.<AddBlazorDesktop>b__0_2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Photino.Blazor.PhotinoBlazorApp.Initialize(IServiceProvider services, RootComponentList rootComponents)
   at Photino.Blazor.PhotinoBlazorAppBuilder.Build(Action`1 serviceProviderOptions)
   at ConfigManager2.Program.Main(String[] args) in D:\source\repos\_Git Repos\CSGO-Projects\ConfigManagerAvalonia\ConfigManager2\Program.cs:line 21
Aborted
```

**Comment by Xyncgas** [comment]
Navigate where ```.\Photino.Blazor.Sample.csproj ``` is and use ```dotnet run``` directly to see if it works
Photino.Blazor is running on MY Fedora so idk how to believe it's not working
I should be educated to learn more

**Comment by Xyncgas** [comment]
Navigate where ```.\Photino.Blazor.Sample.csproj ``` is and use ```dotnet run``` directly to see if it works

**Comment by MathiasLui** [comment]
Thanks for the answer, I was developing on Windows and thought I wouldn't be able to - but forgot VSCode works too.  

Doing what you said, the app runs but only shows the "Loading..." placeholder from the index page -> For both, the `Photino.Blazor.Sample` application as well as mine.  

The first few debug outputs look normal, but then I get:
```
Photino.NET: "{Title of my program}".Load(/)
Photino.NET: "{Title of my program}" ** File "/" could not be found.
Photino.NET: "{Title of my program}".Load(app://localhost/)
```
and for my program specifically, which doesn't seem to matter in this case:
```
({Title of my program}:68428): Gtk-WARNING **: 00:10:52.932: Error loading icon from file 'favicon.ico':
        Failed to load image “favicon.ico”: Compressed icons are not supported
```

The only "/" I could find was the default stuff in the head of the index html `<base href="/" />` and index razor pages `@page "/"` but changing those doesn't change the path in the output from earlier

**Comment by MikeYeager** [comment]
@MathiasLui We are currently updating our samples for the latest Photino version. We will test this during that process.

**Comment by MikeYeager** [comment]
@MathiasLui We have just published Photino.Blazor v3.1.8. Please give it a try. Re-open if you have issues. thanks!

**Comment by MathiasLui** [comment]
Thanks a lot, it doesn't seem to throw an exception on start anymore, though the problem with it not loading still persists, I assume that's not expected since it works on Windows? That or some mistake on my side  

Running the sample app (most recent master) after build or publish, tried as regular, single file or with R2R, built using VS Code:    
![image](https://github.com/user-attachments/assets/21fe2cf4-61b5-4e3f-885e-77ef13c3e4ba)

**Comment by MathiasLui** [comment]
It seems to be the same issue as #124?

**Comment by MikeYeager** [comment]
We will look into this in our next meeting on Thursday.

**Comment by MikeYeager** [comment]
We have identified the issue and are working to resolve it.

**Comment by kimdiego2098** [comment]
any fresh developments?

**Comment by kimdiego2098** [comment]
<PackageReference Include="Photino.Native" Version="3.1.6" />
    <PackageReference Include="Photino.NET" Version="3.1.17" />
    <PackageReference Include="Photino.Blazor" Version="3.1.9" />

Working properly on Ubuntu using Net8  @MikeYeager

**Comment by MathiasLui** [comment]
I just pulled the newest version and the sample app runs for me, too!!
